# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Peter's Portfolio
email: hello@petermueller.io
author: Peter Müller
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.petermueller.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: petermllrr
github_username:  petermllrr

permalink: /:title/

# Build settings
markdown: kramdown

# Footer
footer:
    - text: Email
      url: mailto:hello@petermueller.io
      icon: icon-mail-inline
    - text: Resume
      url: /assets/downloads/resume-peter-mueller.pdf
      icon: icon-cv-inline
    - text: LinkedIn
      url: https://www.linkedin.com/in/peter-m%C3%BCller-51701086/
      icon: icon-linkedin
    - text: Dribbble
      url: https://dribbble.com/petermueller
      icon: icon-dribbble

# Navigation links
navigation:
    - title: Home
      url: /
    - title: Resume
      url: /assets/downloads/resume-peter-mueller.pdf
    - title: Contact
      url: mailto:hello@petermueller.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
---